networks:
  cloudflared_proxy:
    external: true
    
services:

  postgres:
    image: postgres:15
    container_name: pm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - default
      - cloudflared_proxy
  
  fastapi:
    build: .
    image: pm-fastapi:latest
    container_name: pm_fastapi
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGO=${JWT_ALGO}
      - API_PORT=${API_PORT}
      - TRAEFIK_PATH_PREFIX=${TRAEFIK_PATH_PREFIX}
    depends_on:
      - postgres
    networks:
      - default
      - cloudflared_proxy

  # adminer:
  #   image: adminer
  #   container_name: pm_adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
  #   networks:
  #     - default
  #     - cloudflared_proxy