networks:
  traefik_proxy:
    name: traefik_proxy
    driver: bridge

services:

  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.middlewares.dashboard_auth.basicauth.users=loub:$$2y$$05$$Tl0pw8i1I3mWfpsCgheYn.rHh1iBv/kq90SkH4apPaAAX2PeBRk1a/"
      - "traefik.http.routers.dashboard.middlewares=dashboard_auth"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    volumes:
      - ./cloudflared/files:/etc/cloudflared:ro
    command: tunnel --config /etc/cloudflared/config.yml run web-tunnel
    networks:
      - traefik_proxy
    depends_on:
      - traefik
